spring.application.name=springsecurity
#Para local: jdbc:postgresql://localhost:5432/Wolframio
spring.datasource.url=jdbc:postgresql://postgres:5432/Wolframio
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=
spring.jpa.properties.hibernate.transaction.jta.platform=com.atomikos.icatch.jta.hibernate4.AtomikosPlatform
server.port=8084